import { Inter } from 'next/font/google'
import './globals.css'
import { ChatAppProvider } from './Context/ChatAppContext'
import { NavBar } from './Components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChatAppProvider>
          <NavBar/>
          {children}
        </ChatAppProvider>
        </body>
    </html>
  )
}
